export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminUsers } from './AdminUsers'
export { default as AdminPayments } from './AdminPayments'
export { default as AdminCourses } from './AdminCourses'
export { default as AdminSettings } from './AdminSettings'
